name: Build LoveSpace APK

# Dispara o workflow quando há um push para a branch 'main'
on:
  push:
    branches: [ master ]
  # Permite que você rode o build manualmente pela interface do GitHub
  workflow_dispatch:

jobs:
  build:
    # Usa a última máquina virtual Ubuntu do GitHub
    runs-on: ubuntu-latest

    steps:
    # 1. Baixa o código do seu repositório
    - name: Checkout code
      uses: actions/checkout@v4

    # 2. Configura o Java 17
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    # 3. Configura o Flutter
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        cache: true

    # 4. Compila o APK em modo release
    - name: Build APK
      run: cd lovespace
           flutter build apk --release

    # 5. Salva o APK gerado como um "artefato" para download
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: lovespace-apk
        path: build/app/outputs/flutter-apk/app-release.apk