name: Build LoveSpace APK

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # 1. Setup Java (Necessário para o Flutter Android)
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      # 2. Setup Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
      
      # 3. Instalar dependências (Prática recomendada)
      - name: Install Dependencies
        run: flutter pub get

      # 4. Build APK (Removido o 'cd lovespace')
      - name: Build APK
        run: flutter build apk --release

      # 5. Upload APK (Caminho corrigido)
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: lovespace-apk
          # O caminho correto para o APK gerado na raiz do projeto é este:
          path: build/app/outputs/flutter-apk/app-release.apk

      # **OPCIONAL:** Se você precisar do APK para uma release, use a pasta 
      # build/app/outputs/flutter-apk/, pois ela pode ter outros arquivos de build.