name: Build LoveSpace APK

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    # 💡 Dica: Defina o working-directory padrão para a subpasta
    defaults:
      run:
        working-directory: lovespace

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
      
      # Este passo agora encontrará o pubspec.yaml dentro de lovespace/
      - name: Install Dependencies
        run: flutter pub get

      # Este passo agora encontrará o projeto dentro de lovespace/
      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: lovespace-apk
          # Ajuste o path para usar a estrutura da subpasta lovespace
          path: lovespace/build/app/outputs/flutter-apk/app-release.apk